---
permalink:      ":year-:month/:title.html"
markdown:       rdiscount
pygments:       true
auto:           true
server:         true
server_port:    4000
maruku:
  use_tex:      false
  use_divs:     false
  png_dir:      images/latex
  png_url:      /images/latex

header_ref:     '/'    # .html for subdirs, / for main.

gemuser:        infochimps-labs
gemname:        
gemversion:     0.1.0 
title:          infochimps-labs.github.com

keywords:       [ 'ironfan,chef,infochimps-labs,hadoop,gem,ruby,rails,code,hadoop,infochimps,infochimps.com,badass,coders' ]
description:    code repos for Infochimps Labs - @infochimps
header_files:
  - ironfan
  - wukong

  
credits:
