---
permalink:      none
markdown:       rdiscount
pygments:       true
auto:           true
server:         true
server_port:    4000
maruku:
  use_tex:      false
  use_divs:     false
  png_dir:      images/latex
  png_url:      /images/latex

header_ref:     '/'    # .html for subdirs, / for main.

gemuser:        mrflip
gemname:        
gemversion:     0.1.0 
title:          mrflip.github.com

keywords:       [ 'mrflip,gem,ruby,rails,code,scraper,hadoop,infochimps,infochimps.org,badass,coder' ]
description:    code repos for Philip (flip) Kromer - @mrflip
header_files:
  - wukong
  - edamame
  - monkeyshines
  - wuclan

credits:
  
